### ISSUE TITLE
Maybe Ubuntu?

### ISSUE THREAD

**Issue by idvoretskyi** [CBPP/cbpp#1]
Does anybody know, what was the reason of switching the original Crunchbang from Ubuntu sources to Debian?

What do you think about returning to Ubuntu codebase due to some features that allows people to prefer *buntu-based distributives to use on their desktops instead of Debian?

**Comment by computermouth** [comment]
I know where you're coming from. In fact, for a few friends I've set up computers with the Ubuntu netinstall and just added the crunchbang metapackage on top of it. For us currently, the plan is still Debian. However, if you find yourself so interested, I don't see any immediate reason why our sources here couldn't be build _exactly_ the same way on an Ubunutu host! If you give it a shot, let us know how it goes and maybe then we could offer it as an alternative!

**Comment by nfultz** [comment]
From forums:

http://crunchbang.org/forums/viewtopic.php?pid=45682%23p45682#p45682

**Comment by computermouth** [comment]
Maybe further down the line, it will be offered as an option. Most/all of the changes that are being made will actually make the package set much more portable.
