### ISSUE TITLE
Update cb-welcome

### ISSUE THREAD

**Issue by AlexDaniel** [CBPP/cbpp#10]
I've done a couple of huge commits to cb-welcome in the past, and it seems like my version is the most recent one (look here: https://github.com/corenominal/cb-welcome/network). It even comes with a localization support (wow, I was wild).

**Comment by AlexDaniel** [comment]
These are my pull requests (you can find detailed description there):
https://github.com/corenominal/cb-welcome/pull/8
https://github.com/corenominal/cb-welcome/pull/9
I hope it gives you the motivation to upgrade these scripts :)

**Comment by computermouth** [comment]
Oh wow, you weren't kidding. These look great! We were also playing with the idea of adding in a few non-debian-repo applications that have .debs available (steam, smxi, atom, maybe vivaldi and/or midori, possibly android studio), so be sure to keep an eye on this one once it's split from the main repo here.

Or perhaps those should be saved for pipemenus. Though, the original does have LibreOffice in both cb-welcome and pipemenus. Maybe we'll just do both?

Also, if you or anyone has recommendations for newer non-repo packages, I'm open to suggestion.

**Comment by AlexDaniel** [comment]
A note for myself:

```
sudo cat "$A2D/default" | sed '9,14 s/AllowOverride None/AllowOverride All/' > "$A2D/default2"
sudo mv -f "$A2D/default2" "$A2D/default"
```

Wow, I wonder why I did not refactor it to inplace editing:

```
sed -i '9,14 s/AllowOverride None/AllowOverride All/' "$A2D/default"
```

Yea, I'm willing to maintain these scripts, can't wait for you to split it into another repo. Although I don't really care about software selection, I really want the code to make sense. Basically I stopped making any pull-requests because corenominal stopped working on #!, thus some of my pull requests were not accepted or even commented. I'm really happy that I can continue doing this stuff.

**Comment by computermouth** [comment]
That sounds fantastic. Bash isn't really a strong point for me. I've learned a ton already just digging through the few packages that have scripts though. 

_I'm really happy that I can continue doing this stuff._ --that is essentially our unofficial motto :)

Also, so far, there have been a few things that have basically become obsolete based on how we're installing it. Some scripts manually making changes to the userspace from /etc/skel, which was causing issues with the initialization of the user. So, I imagine I may have to hit you up for any similar problems there.

**Comment by computermouth** [comment]
Oops, didn't mean to close. CBPP/cbpp-welcome is now its own repo! This is using the latest version that was from the #! repos, so we'll still have to add these pull requests. For now, I'm working on getting the cbpp repo up and running so that we can actually test these and the pipemenus out. Otherwise cbpp-welcome should be fully functional on the surface, it just won't install any of the packages until the repo is up and added to sources.list.

When the repo gets up, I'll be doing a word-of-mouth Beta2 so we can actually deploy the changes and use them in a live environment.

**Comment by AlexDaniel** [comment]
@computermouth
Today I've tried moving the commits from [my repo](https://github.com/AlexDaniel/cb-welcome) to CBPP/cb-welcome. This is impossible. At first I thought that I only have to adapt these patches to the new directory structure, but then I found out that most of the stuff inside the files was renamed from cb- to cbpp. I see no way to move these commits, the only way is just to replace the files and rename stuff again. Feel free to do that yourself.

**Comment by computermouth** [comment]
Ah, I hadn't thought of that, sorry. I'll probably give it a shot this weekend.

**Comment by computermouth** [comment]
Merged your fork, changed branding. So far so good.

**Comment by AlexDaniel** [comment]
@computermouth as far as I can see, the "translations" folder is a bit misplaced. But at the same time I cannot tell where it should be. Not off the top of my head, at least. I'll have a look a bit later.
