### ISSUE TITLE
Update cb-pipemenus

### ISSUE THREAD

**Issue by AlexDaniel** [CBPP/cbpp#11]
This one is a little bit complicated:
https://github.com/corenominal/cb-pipemenus/network
A bunch of my commits were accepted by corenominal (https://github.com/corenominal/cb-pipemenus/pull/6), then there were two commits after that, but then TamCore has done a lot of work on top of that (I'm not sure whether it is arch-specific or not). And there is also some stuff by johnraff. Have a look.

**Comment by computermouth** [comment]
Haven't forgotten this one. After the cbpp-configs are done, I'm coming after this.

**Comment by AlexDaniel** [comment]
It has been just 4 days. Take your time! :)

**Comment by amharris** [comment]
@computermouth 
I've interestingly had these break like crazy (and had to reimplement from an image of CrunchBang, along with a few other cb components) when installing proprietary graphics drivers. It also shifted around a few CB UI elements, such as the log in screen (after recovering from command-line only access post-install upon rebooting).
It'd be worth doing some testing with this for CBPP. I'd be perfectly happy to volunteer here.

**Comment by computermouth** [comment]
These issues could stem from few things. For the pipemenus, the executables' names are hardcoded, and the condition for checking where they're installed is 'if file exists /usr/bin/chromium-browser'. The bummer there is that chromium-browser is now just chromium. That said, I really can't think of a better way to do it to be more fluid. Sure, it could check for the package, but there's not really an elegant way to search for the primary executable within that package.

The log in screen changing has been a problem with doing these updates too. For some reason, the file that sets the theme /etc/slim.conf is rewritten with every package! In crunchbang, this seems to have been solved by pinning the repo in order to not upgrade the package until corenominal remade the package. I really don't want to do that. But we'll see.

**Comment by AlexDaniel** [comment]
@computermouth 
`if which chromium; then echo 'ok'; else echo 'none'; fi`
or
`if type chromium; then echo 'ok'; else echo 'none'; fi`

Actually, I don't really understand what is going on here. I've opened this issue to inform you about refactored cb-pipemenus script that I worked on a few years ago. The issue you are talking about (tool check is done via checking /usr/bin/) is fixed there. And instead of pulling these changes you are continuing to add changes to the outdated, poorly written script, trying to reinvent the wheel that was invented more than a year ago. Why?

The problem is that cb-pipemenus and cb-welcome have diverged so much in your repos that I cannot create meaningful patches anymore. The only way to pull them now is to replace all of the files, and then apply your changes one by one. At least that's the easiest solution I can see.

**Comment by computermouth** [comment]
Firstly, the goal was to produce stability as quickly as possible. Making small patches was the quickest way to do so. Second, I just kind of forgot. Third, I'd rather understand the issues, patch them, then pull the new ones in. The more I can learn about these scripts, the better. Besides, my changes are mostly just replacing cb- with cbpp-

**Comment by AlexDaniel** [comment]
Well, if you're not going to pull that it, then we can close this issue? As well as that one https://github.com/CBPP/cbpp/issues/10

**Comment by computermouth** [comment]
Oh, I'm building/testing it right now.

**Comment by computermouth** [comment]
Alright, as of now, it's up to where corenominal's master repo is, with my naming changes. I haven't gotten a look at your two uncommitted pulls yet (just wanted to make sure I could get the base running stable first). I did look at TamCore's but they all do indeed seem to be more or less Arch specific.

There are two (relatively) minor issues with cbpp-pipemenus right now:
1. Before and after installation, pipemenu lists the Openbox entry as 'Install Google chrome stable' and 'Google chrome stable' respectively.
2. The entry for launching Chrome into incognito mode does not appear.

These are surely related to how google-chrome is now google-chrome-stable. I changed the entry in TOOLS=(...) and had to change the function to 'setupGooglechromestable'. Obviously there's some bash magic that concatenates/formats the openbox menu launcher flag to use the package name to generate the entry text, but I can't wrap my head around why it works for two-words, but not three-other-words.

**Also, if you'd like, I could host a current image if you'd like to have a look in person.

**Comment by AlexDaniel** [comment]
Well, previously it was all just copy-pasted code. Now there is just a list of packages + some magic, yeah. I'm sure, a little bit of trickery is better than the ugliness of the copy-pasted stuff.

However, there is one thing that rendered the whole code into useless crap :(
This code `a='hello world'; echo "${a~}"` produces different output in different bash versions.
bash 4.2
**Hello World**
bash 4.3
**Hello world**
And I was stupid enough to use that undocumented feature. I'll fix that in a pull request.

The function must be called `setupGoogleChromeStable` (although currently it will only work with `setupGooglechromestable`). If you tried `setupGooglechromestable` then it should have worked.

**Comment by computermouth** [comment]
^Correct, that does work. I've also since pushed in the 'type [whatever]' pulls you made. I left out the spacing/layout changes, but if you'd like to pull those: by all means.

**Comment by AlexDaniel** [comment]
This issue is solved now (we are using the most recent code now). If there are any other problems - feel free to open new issues :)
