### ISSUE TITLE
Get rid of cb-wmhacks

### ISSUE THREAD

**Issue by AlexDaniel** [CBPP/cbpp#15]
Read my post here:
http://crunchbang.org/forums/viewtopic.php?pid=350713#p350713

Since we don't have pvsage here, we can finally get rid of redundant crap :)

**Comment by computermouth** [comment]
Personally, I've always used aerospace for quick window adjustments, but always only as a replacement for the kind of window snapping that you get from other fancier DEs. Could anyone recommend a snap-to replacement?

**Comment by AlexDaniel** [comment]
@computermouth what kind of "snap-to" exactly?

**Comment by computermouth** [comment]
Essentially, I'd love the functionality that cb-wmhacks is supposed to be providing. The Windows-esque push-against-a-wall->resize-to-that-half-of-the-screen is a nice feature. It looks like cb-wmhacks is supposed to provide that. Granted, I've never looked much into editing it or turning it on if it's disabled by default. But I think it'd be a good thing to have if we can get it reliably working this way by default. But it's also fairly low on the priority list.

**Comment by AlexDaniel** [comment]
Well, did you click on the link in my forum post? http://openbox.org/wiki/Help:Actions#MoveResizeTo
Openbox can do that natively.

**Comment by computermouth** [comment]
Oh, sorry, I skimmed over it. I'll get to reading it in full soon. Also, I'll see if i can get cb-wmhacks put into its own repo tonight and then dive into it. Right now, dragging a window against an edge pushes the window to the next workspace with the default setup. If we could get that changed to resizing in the current workspace, that'd be pretty slick.

**Comment by computermouth** [comment]
I see what you mean now. Ran a test build without them too, just to be sure. Everything's good, purged from repo!

**Comment by AlexDaniel** [comment]
I'm not sure if this should be closed. Well, you removed it, but at the same time there is no offered replacement. I mean, maybe we should put something into openbox config file so that people can start using it just by uncommenting some lines? Also, maybe we need a small page on the wiki telling people how to make a transition from cb-wmhacks to openbox native functionality and xdotool?

**Comment by computermouth** [comment]
How about, we build the package, but not include it by default? It's likely any user specifically looking for it, knowing its name and understanding functionality, would be able to apt-get it from the repo we're planning on setting up?

**Comment by AlexDaniel** [comment]
Well, that's not bad. But still I feel like we're carrying the weight of a dead horse. Just keep it open, there is a high chance that I or someone else will get his hands on it and clarify the exact steps to replace cb-wmhacks functionality.

**Comment by computermouth** [comment]
cb-wmhacks was replaced with a new set of openbox macros for snapping to halves of the screen.

**Comment by AlexDaniel** [comment]
great!
