### ISSUE TITLE
Date format on website and e.g. torrent filenames

### ISSUE THREAD

**Issue by scooper22** [CBPP/cbpp#16]
Hi Ben,

I've been looking for ways to contact you directly but it's impossible, so I make a new git issue.

On the cbpp website blog and in the torrent filenames you use the date notation
"month.day.year", for example "https://crunchbangplusplus.org/CBPP_beta_02132015.torrent"

I have no idea from which region of the world you are from (I suspect England or a colony) but to me it was irritating at first sight :)
That's however not the issue - the issue is, filenames with this scheme do not sort pretty well.
So when I have several torrent files or whatever in my cbpp-folder they are a total mess as the filename sorting does not correspond to the "most recent" informal date sorting, which is IMHO an issue.

Why not look at, e.g. https://en.wikipedia.org/wiki/ISO_8601 or just make them in the format "year.month.date", which sorts nicely in the folder list, with the most recent file always at the bottom (or top depending on sorting)

On your blog, okay, like I said, it's very confusing to me, but that's artist's freedom but for filenames it's not pretty well chosen as technically impractical.

Hope to hear from you,
Dirk

**Comment by computermouth** [comment]
Thanks for the tip, for now the torrent and its files will have to stay that way, but for the next releases it'll be changed. Also, you can reach me at computermouth@crunchbangplusplus.org or on my twitter @computermouth.

**Comment by AlexDaniel** [comment]
ISO 8601 is YYYY-MM-DD, not YYYY.MM.DD. And yes, it is the only date format that makes sense.
