### ISSUE TITLE
Should we drop tint2conf?

### ISSUE THREAD

**Issue by computermouth** [CBPP/cbpp#17]
I never even knew this existed before starting this project. It seems to not actually work and there's been no development for over four years.

https://code.google.com/p/tint2/downloads/list

The tint2conf page says it's still under development, and that message was dated 5 days ago. But downloading the source, it's not received any changes for about four years either. I'm leaning towards tossing it.

**Comment by AlexDaniel** [comment]
Also, tint2conf conflicts with the tint2 package from debian jessie repo because tint2 package contains tint2conf.

**Comment by computermouth** [comment]
Unfortunately, the jessie package is also broken. Which is a terrible shame. I'd love a quick-edit tint program. Oh well, I suppose it'll be in by default then. Thanks Alex!
