### ISSUE TITLE
Updated Conky script?

### ISSUE THREAD

**Issue by computermouth** [CBPP/cbpp#18]
I think the original is near-perfect. That said, corenominal's posted one here: http://crunchbang.org/forums/viewtopic.php?id=59

...has been my GOTO for a while. I'd like to merge the default with corenominal's posted one.

SYSTEM INFO
Host: default
Uptime: default
CPU: graph
Memory: bar
DISK IO: graph
Disk Usage: bar
Swap Usage: bar

SHORTCUT KEYS
default default etc. etc.

(where graphs are obviously the tall graphs and bars are the thin horizontal meters)
Preferrably all in the stock grey color that the default config is in.

Networking can be omitted cuz it's a pain, unless someone wants to set it up to combine all network stats for eth0 wlan0 and ath0 into one.

**Comment by AlexDaniel** [comment]
Maybe CPU temperature? That was pretty easy as far as I remember.

**Comment by computermouth** [comment]
Unfortunately, it seems somewhat unreliable in terms of availability and dependability, varying by hardware. I've actually had a few computers over time that refused to show proper CPU temperature, returning -255C or 'null' etc.

**Comment by overlandandseas** [comment]
Should we store additional conky scripts on the site or just package them in the repo? I still have that is different but super useful to me. Only problem stuff like batterie jumps all over the place.

**Comment by computermouth** [comment]
We're sticking with the original for now. Suggestions are still welcome, but not really an "issue". Just trying to clean some of these up. Particularly since this is the future home of the build instructions.

**Comment by overlandandseas** [comment]
Yeah, /r/conkyporn is a good enough job of helping people out and showcasing some awesome ones.
