### ISSUE TITLE
Let's stop using a silly license in new files

### ISSUE THREAD

**Issue by AlexDaniel** [CBPP/cbpp#19]
WTFPL is a silly choice, let's use something else for new files.

If we want to keep it the same way, then [CC0](https://en.wikipedia.org/wiki/Creative_Commons_license#Zero_.2F_public_domain) (in other words Public Domain) is the right choice. It is almost identical to WTFPL.

However, the most popular free software license is GPL, so maybe we should consider using it. There is a deep [philosophy](http://www.gnu.org/philosophy/philosophy.html) behind it

**Comment by jrgifford** [comment]
While I'm just an observer, I regard the GPL as a philosophical license, not a practical one. Perhaps something like MIT or CC0 would be appropriate?

**Comment by computermouth** [comment]
I'm actually most familiar with GPL. I do like MIT as well. Initially I was setting everything up with public domain, however, the primary reasons I left it at WTFPL:
1. That license is essentially the only reason we are able to continue the project with this name and reuse the same packages with complete freedom.
2. The SSL provider that approved our website for a _free_ SSL cert (normally their service is in the $800/year range) approved the project based on it's Open Source nature, but has very distinct rules about what licenses apply. Public Domain is a grey area for them.

In the end, I know where your coming from (and even felt that way myself initially), but I'd like people to have the same freedoms that we've had with the packages, and I think keeping WTFPL is the best way to maintain that.

**Comment by AlexDaniel** [comment]
So do I get it right that we should use CC0 for new files? It has exactly the same rules, just without a silly name.
Your second point makes no sense to me. WTFPL is almost identical to Public Domain...

**Comment by AlexDaniel** [comment]
https://www.gnu.org/philosophy/license-list.html
CC0 is listed alongside of WTFPL, both are free software licenses.

**Comment by computermouth** [comment]
WTFPL releases any/all protected ownership if anyone desires. Creative Commons does not. Like I said, WTFPL is literally the only reason that we're able to do what we're doing here to the extend that we're doing it. Aside from that, it's what was used for the original packages. This software was intended to be distributed that way, and it will remain that way. I agree, it's a little obnoxious, but as seen on the #! forums, it fits the project ;)

**Comment by AlexDaniel** [comment]
Are you sure that your answer is well thought out? I mean, look:

> That license is essentially the only reason we are able to continue the project with this name and reuse the same packages with complete freedom.
> 
>  Like I said, WTFPL is literally the only reason that we're able to do what we're doing here to the extend that we're doing it.

Like, err, what? Even if the original code was released under any strict license like GPL, nothing would stop you from continuing the project. What kind of a possible restriction are you talking about?

Actually, WTFPL is the only thing that could stop you from continuing the project because it might not make any legal sense.

> WTFPL releases any/all protected ownership if anyone desires. Creative Commons does not.

Can you explain this? Are you sure that you're talking about CC0?

**Comment by mosamy** [comment]
I am also an observer here also, when I checked the Debian license here is what they said
"We welcome enquiries from maintainers considering particular licenses, but we encourage most maintainers to use one of the common licenses: GPL, LGPL, modified BSD, or Artistic."

So I see the Debian people endorsing GPL and BSD.

As long as we can continue and keep going.

WTFPL is a funny name and I agree it fits the project. But could someone tell me how this could possibly have any effect on things going forward either way?

**Comment by AlexDaniel** [comment]
> But could someone tell me how this could possibly have any effect on things going forward either way?

It does not have any huge effect, but we have a golden opportunity to change the license early on.

**Comment by computermouth** [comment]
Sorry fellas/ladies, the license stays.

I was wrong about CC0 though, I stopped reading when it said Creative Commons. I just really don't think we'd benefit from another license, that we'd be harmed by using WTFPL, or that the project warrants a more serious license.
