### ISSUE TITLE
Put website sources (https://crunchbangplusplus.org/) on GitHub

### ISSUE THREAD

**Issue by AlexDaniel** [CBPP/cbpp#24]
Because why not.

The suggested license is AGPLv3.

**Comment by overlandandseas** [comment]
It's being updated constantly and it's currently just static html/css pages so view source will give you 100% what it is. I will put it up here once it's a lot not nicer and actually interesting.

**Comment by AlexDaniel** [comment]
@Overlandandseas well, putting it on GitHub allows others to make it a lot nicer and interesting, I think. That's one of the reasons why people share their stuff - to allow others to help in a meaningful way.

**Comment by computermouth** [comment]
Done!

https://github.com/CBPP/crunchbangplusplus.org
