### ISSUE TITLE
Website: CBPP is not completely free.

### ISSUE THREAD

**Issue by AlexDaniel** [CBPP/cbpp#25]
Since there is no repo for the website (https://github.com/CBPP/cbpp/issues/24) I am starting an issue here.

It says on the website:

> CrunchBang++ is an open source and completely free computer operating system

I'm not sure what is going to happen with #!++, but #! itself was not a _completely_ free operating system. It is not free in the terminology of both FSF and Debian, because it contains lots of proprietary (non-free) drivers by default.

Even if you don't agree with such terminology, please remove the word "completely".
The list of entirely free distributions is here: http://www.gnu.org/distros/free-distros.html

**Comment by computermouth** [comment]
Noted, I didn't write the About page. It's been changed to reflect that it's free of cost, but not "Free as in freedom."
