### ISSUE TITLE
Remote file systeme (Gigolo) only have "Custom location" as service type

### ISSUE THREAD

**Issue by ghost** [CBPP/cbpp#27]
The real issue is that it's the gvfs-backends that's not install during bootstrap. Once it's install by hand Gigolo work as in waldof. I would be a good idea to integrate it in the additional package.

**Comment by computermouth** [comment]
Noted! I'll add it to the package list and metapackage dependencies. Thanks

**Comment by computermouth** [comment]
gvfs-backends was added to the current image before release. Resolved!
