### ISSUE TITLE
No non-PAE Support

### ISSUE THREAD

**Issue by iamunknown2** [CBPP/cbpp#28]
Not exactly an issue, but the good thing about the original CB was that you could run the minimalist OS on very old hardware. Perhaps a non-PAE version?

**Comment by computermouth** [comment]
While it's been requested a few times, I imagine the number of people who'd actually use it would be smaller than the number of people who'd accidentally download it.

HOWEVER!
Soon, I will be publishing the build instructions here, and you should be able to build your own quite easily! (I've scripted the build, so all that would need to be run is './build') And theoretically, you'd have a non-PAE build in less than an hour!

**Comment by iamunknown2** [comment]
Yay!

**Comment by kurgol** [comment]
any updates on this - someone was asking again on reddit for a PAE build?

**Comment by BelleNottelling** [comment]
I was able to boot `cbpp-9.0-i386-20170621.iso` on [v86](https://github.com/copy/v86) which has no PAE support.
