### ISSUE TITLE
Provide safer hash sum to verify download

### ISSUE THREAD

**Issue by lucasrogeriomasotti** [CBPP/cbpp#37]
Currently only the MD5 sum is provided. According to its Wikipedia article: " it has been found to suffer from extensive vulnerabilities. It can still be used as a checksum to verify data integrity, but only against unintentional corruption".
Since we don't have direct links and some people may download the ISO from different places, it would be nice to provide the SHA-256 or SHA-512 sums as a method to safely verify you have the right file.

**Comment by kurgol** [comment]
As a tempoary measure until @computermouth has a chance to view this I have generated sha512's for both the amd64 and i386 builds:

```
$ /usr/bin/sha512sum cbpp-9.0-amd64-20170621.iso
736e0fd6dc276d937a9772a63a766948138d9dfe9d9bf9c944e35330acdcaf15542e31fc44085d4597c60a79b23bd9aad18d2d65e5f39c3a1f7ce7b33e8410b2  cbpp-9.0-amd64-20170621.iso
$ /usr/bin/sha512sum cbpp-9.0-i386-20170621.iso
052ef9824ff970a968bd9558c1ae17a448ef668d7f4ab1ee95becdd694006d284f60ea9ce6bdd44683ec185f3e3c0f49db9120f6ec1935740bc58b547683ee51  cbpp-9.0-i386-20170621.iso
```

These are both images I have personally downloaded, tested they match the published md5's - it may give you some extra assurance until legitimate signatures are provided - good idea though.
