### ISSUE TITLE
Can't run or re-install gparted, parted and fdisk

### ISSUE THREAD

**Issue by korbendallaskoop** [CBPP/cbpp#45]
cbpp-10.1-amd64-20190713

Pardon a debian noob if this is a trivial apt non-issue but I couldn't open gparted nor install it as it is 'set to manually installed' according to apt. 
Both on live iso and install.
It can be removed but afterwards not installed (no candidate).

Same for parted and fdisk, no bins in terminal or d-menu.

Thanks for your supremely tasteful openbox rice btw. 

![image](https://user-images.githubusercontent.com/45145001/82613520-bf62b080-9bc5-11ea-942c-a3f02f625d11.png)

![image](https://user-images.githubusercontent.com/45145001/82614308-d1dde980-9bc7-11ea-88ce-8b2709204e43.png)

![image](https://user-images.githubusercontent.com/45145001/82613437-92ae9900-9bc5-11ea-86d7-3f2956559953.png)

Post-install apt came up with 110mb of not used anymore packages to be autoremoved , not sure if that's expected or relevant here so hereby mentioned as well:

```
cbpp@cbpp:~$ sudo apt install gparted
[sudo] password for cbpp: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gparted is already the newest version (0.32.0-2).
gparted set to manually installed.
The following packages were automatically installed and are no longer required:
  atril-common fonts-mathjax gstreamer1.0-gl gstreamer1.0-plugins-good
  gstreamer1.0-pulseaudio gstreamer1.0-x libbrotli1 libcaja-extension1 libdv4
  libept1.5.0 libgail-3-0 libgraphene-1.0-0 libgstreamer-gl1.0-0
  libharfbuzz-icu0 libhyphen0 libiec61883-0 libjavascriptcoregtk-4.0-18
  libjs-mathjax libmicrodns0 libv4l-0 libv4lconvert0 libwoff1
  python-asn1crypto python-bcrypt python-cffi-backend python-cryptography
  python-enum34 python-ipaddress python-nacl python-paramiko python-pyasn1
  python3-distro yelp-xsl zenity-common
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by computermouth** [comment]
This is because gparted is only in root's PATH, not a regular user's PATH. This is expected behavior, you can however `sudo gparted`

```
$ which gparted
// nothing
$ sudo su -
# which gparted
/usr/sbin/gparted
```
