### ISSUE TITLE
Nitrogen doesn't show new directory after first time

### ISSUE THREAD

**Issue by corey851** [CBPP/cbpp#49]
Environment: newly installed and updated cbpp on physical hardware - Acer Aspire.
In the Nitrogen preferences I added a directory (~/.backgrounds).  It displayed the contents of the directory and I could select a new wallpaper file.  (It worked fine.)
If I close Nitrogen and reopen it the files from the new directory are not there to choose from anymore.  The added directory is still in the list but no files from that directory are displayed as selectable.  

Update: After troubleshooting for a while I found a fix. 

In menu.xml change
	`<execute>nitrogen ~/images/wallpapers/</execute>`
to just
	`<execute>nitrogen</execute>`

**Comment by computermouth** [comment]
Merged, thanks!
https://github.com/CBPP/cbpp-configs/commit/0788784b42b5e68dc47bc9b03fae74f8d17cfbd7
