### ISSUE TITLE
User Interface Settings don't take until reboot

### ISSUE THREAD

**Issue by corey851** [CBPP/cbpp#50]
Environment: new cbpp install and update on physical hardware. 

I'm trying to change the icons with the User Interface Settings (LXAppearance) utility.  The changes do not take effect until I reboot.
I tried Openbox > Reconfigure and Openbox > Restart but these don't fix it.  Only the reboot worked.  
I didn't even add any new ones, just testing with the provided icons such as CBPP and GNOME.

**Comment by computermouth** [comment]
This is expected behavior for gtk3, and probably also gtk4. gtk2 can update in realtime, but the others do not.
