### ISSUE TITLE
Create an organization on Github

### ISSUE THREAD

**Issue by AlexDaniel** [CBPP/cbpp#7]
Create a CBPP organization on Github (so that you can group all cbpp repos). Otherwise it would be hard to distinguish your other repos from CBPP-related ones.

**Comment by computermouth** [comment]
I did create the organization, having a hard time moving this repo to it though. If the new repo is at CBPP/main-src.git what do I need to do?

**Comment by AlexDaniel** [comment]
I believe that all you have to do is:
1. Go to your repo on github.com (https://github.com/computermouth/cbpp)
2. Click on "Settings"
3. Scroll down to Danger zone
4. Use "Transfer ownership". Transfer it to your organization.
That's it, I guess.

**Comment by computermouth** [comment]
Oh, that was much easier than the git commands I was digging through. Thanks!

**Comment by AlexDaniel** [comment]
The organization thingy is GitHub specific, so none of the git commands would work :)
