### ISSUE TITLE
Use Jessie terminator, update openbox configs and cb-scripts to use x-terminal-emulator symlink

### ISSUE THREAD

**Issue by nfultz** [CBPP/cbpp#9]
On the #! forums, several people (myself includeded) have tried to change out the terminal in #!, but terminator is hardcoded in many, many places. The first step to fixing this is to use the Jessie version of terminator, which properly supports x-terminal-emulator.

**Comment by computermouth** [comment]
Just to make sure I'm following properly, this is strictly to allow easier transition between default terminals, correct? As far as using new packages goes, have a look at the other similar issue you posted.

**Comment by nfultz** [comment]
Right, when someone changes their default terminal it would be good if the
openbox menu items and cb scripts respected that instead of always showing
terminator.

The wheezy version of terminator didn't honor x-terminal-emulator arguments
properly, which is why the config changes were never made upstream.

This has been brought up often enough:

http://crunchbang.org/forums/viewtopic.php?pid=413341
http://crunchbang.org/forums/viewtopic.php?pid=413294
http://crunchbang.org/forums/viewtopic.php?pid=334202

and my topic from 2013 :
http://crunchbang.org/forums/viewtopic.php?pid=308104

and the launchpad bug:
https://bugs.launchpad.net/ubuntu/+source/terminator/+bug/366644

**Comment by computermouth** [comment]
Cool, thanks for clarifying. I believe I've found all hardcoded instances. It's on the list for tomorrow (unless you'd like to throw in some pulls for it!), then I'll generate an .iso and check it out.

So far, the file list:
cb-pipemenus:
--places
--x-www-browser
--libreoffice
--printing
--sshconfig
--compositor
--remote-desktop

And in cb-welcome, but that shouldn't be an issue unless anyone plans on building from this source bundle with a different terminal in place from install. But I suppose it couldn't hurt!

**Comment by nfultz** [comment]
cb-configs was the one I most cared about, eg: 
https://github.com/nfultz/cb-configs/commit/d836262031a63fd7171538ec1c71fb7e3e313d76

**Comment by nfultz** [comment]
Sent you a pull req for the openbox configs.

**Comment by computermouth** [comment]
Excellent, thanks! Going to leave this open until I can get to the cb-scripts as well.

**Comment by computermouth** [comment]
nfultz, I've applied your commits. Side note: this repo is going to get out of hand pretty quickly. I'm making some changes to the ways I was building the packages as well. To keep things more streamlined, I'm going to separate each package into it's own repo. cb-configs is the first out, since (functionally), it's good to go. So now, keep in mind the package will be under CBPP/cbpp-configs (also changing packages from cb-\* to cbpp-*).
